version: '3.7'

services:

  database:
    image: postgres:14.3
    env_file:
      - .env
    networks:
      - biotech

  backend:
    image: ghcr.io/biotech-h/backend:v1.0.0
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      - biotech

  crowleer:
    image: ghcr.io/biotech-h/crowleer:v1.0.0
    env_file:
      - .env
    environment:
      - LOGLEVEL=DEBUG
    networks:
      - biotech

  frontend:
    image: ghcr.io/biotech-h/frontend:v1.0.1
    env_file:
      - .env
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
    ports:
      - 8081:8081
    networks:
      - biotech

networks:
  biotech:
