version: '3.7'

services:

  database:
    image: postgres:14.3
    env_file:
      - .env
    networks:
      - biotech

  backend:
    image: ghcr.io/biotech-h/backend:v1.0.0
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      - biotech

networks:
  biotech:
